function RENAMEiscellTOisCell_C2S(fileName, FallDataLocation)

%This function renames the iscell variable in the Fall.mat file to isCell.
%The Fall.mat file is generated by the Suite2p.

tempVar= load(strcat(FallDataLocation,fileName));

isCell = tempVar.iscell;
clearvars tempVar
load(strcat(FallDataLocation,fileName));
clear iscell

lastBackslashIndex = find(FallDataLocation == '\', 1, 'last');
% Crop the text until the last backslash, this changes the folder path containing the selected Fall.mat file
cd(FallDataLocation(1:lastBackslashIndex - 1))

clear FallDataLocation fileName lastBackslashIndex

save('Fall.mat')