function d = ErrorCallback_C2S(d)

try
set(d.GUI.errorConsole,...
    'String', strcat('[',string(datetime('now', 'format',"HH:mm:ss")),']',{' '},...
    d.errors.latestReturned));
catch
    set(d.GUI.errorConsole,...
    'String', strcat('[>>] ',...
    d.errors.latestReturned));
end