function pb = GenericPushButton_C2S(F)
%creates a generic pushbutton on a given figure F;

defaultString = '';
defaultUnits = 'Normalized';
defaultPosition = [0 0 0.1 0.1];
defaultBackgroundColor = 'White';
defaultForegroundColor = 'Black';
defaultFontSize = 10;
defaultTag = 'notag';
defaultFontWeight = 'Normal';


pb = uicontrol(F,'Style', 'Pushbutton',...
    'String', defaultString,...
    'Units', defaultUnits,...
    'Position', defaultPosition,...
    'BackgroundCOlor', defaultBackgroundColor,...
    'ForegroundColor', defaultForegroundColor,...
    'FontSize', defaultFontSize,...
    'Tag', defaultTag,...
    'FontWeight', defaultFontWeight);