function d = LogCallback_C2S(d)

try
set(d.GUI.loggingConsole,...
    'String', strcat('[',string(datetime('now', 'format',"HH:mm:ss")),'] ',...
    {' '}, d.logging.latestReturned));
catch
    set(d.GUI.loggingConsole,...
    'String', strcat('[>>] ',...
    d.logging.latestReturned));
end